a = input('digite algo')
print('o tipo primitivo desse valor é: ', type(a))
print('só tem espaços? ', a.isspace() )
print('é um numero ?, ', a.isnumeric())
print('pe alfabético? ', a.isalpha())
print('é alfanumérico? ', a.isalnum())
print('etpa em maiúsculas? ', a.isupper())
print('está em minúsculas? ', a.islower())
print('é capitalizada? ', a.istitle())